title: AbhishekSubbu
url: https://abhisheksubbu.github.io/
description: Sharing my thoughts on the Cloud
paginate: 6
paginate_path: "/blog/page:num/"

baseurl:
repository: "abhisheksubbu/abhisheksubbu.github.io"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge

permalink: /:title/
disqus_shortname: abhisheksubbu-github-io

plugins: [jekyll-paginate]
