title: AbhishekSubbu
tagline: Sharing my thoughts on the Cloud
url: https://abhisheksubbu.github.io/
description: Sharing my thoughts on the Cloud
author: Abhishek Sivasubramanian

twitter:
  username: abhisheksubbu
  card: summary

social:
  name: Abhishek Subbu
  links:
    - https://twitter.com/abhisheksubbu
    - https://www.linkedin.com/in/abhisheksubbu
    - https://github.com/abhisheksubbu
    - https://www.youtube.com/channel/UCkh6ynIz3HU0eKYDxuCEGyg

google_site_verification: 6nqFBgZdK0gATjDa3ZO3lJ11cpSDhxDmJOhqUs15IFs

paginate: 10
paginate_path: '/blog/page:num/'

baseurl:
repository: 'abhisheksubbu/abhisheksubbu.github.io'

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge

permalink: /:title/
disqus_shortname: abhisheksubbu-github-io

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
